
#include "CountryCodes.h"

CountryCodesModelItem::CountryCodesModelItem (const QString & name, const QString & flag, const QString & code, QObject * parent)
    : QObject { parent }
    , m_name  { name }
    , m_flag  { flag }
    , m_code  { code }
{ }

bool CountryCodesModelItem::match (const QString & filter) const {
    return (filter.isEmpty () || m_code.contains (filter) || m_name.contains (filter, Qt::CaseInsensitive));
}

CountryCodes::CountryCodes (QObject * parent)
    : QObject { parent }
    , m_list  { new QQmlObjectListModel<CountryCodesModelItem> { this } }
{
    m_list->append ({
                        new CountryCodesModelItem { "Afghanistan", "qrc:///RegionFlags/png/AF.png", "93" },
                        new CountryCodesModelItem { "Albania", "qrc:///RegionFlags/png/AL.png", "355" },
                        new CountryCodesModelItem { "Algeria", "qrc:///RegionFlags/png/DZ.png", "213" },
                        new CountryCodesModelItem { "American Samoa", "qrc:///RegionFlags/png/AS.png", "1684" },
                        new CountryCodesModelItem { "Andorra", "qrc:///RegionFlags/png/AD.png", "376" },
                        new CountryCodesModelItem { "Angola", "qrc:///RegionFlags/png/AO.png", "244" },
                        new CountryCodesModelItem { "Anguilla", "qrc:///RegionFlags/png/AI.png", "1264" },
                        new CountryCodesModelItem { "Antigua and Barbuda", "qrc:///RegionFlags/png/AG.png", "1268" },
                        new CountryCodesModelItem { "Argentina", "qrc:///RegionFlags/png/AR.png", "54" },
                        new CountryCodesModelItem { "Armenia", "qrc:///RegionFlags/png/AM.png", "374" },
                        new CountryCodesModelItem { "Aruba", "qrc:///RegionFlags/png/AW.png", "297" },
                        new CountryCodesModelItem { "Australia", "qrc:///RegionFlags/png/AU.png", "61" },
                        new CountryCodesModelItem { "Austria", "qrc:///RegionFlags/png/AT.png", "43" },
                        new CountryCodesModelItem { "Azerbaijan", "qrc:///RegionFlags/png/AZ.png", "994" },
                        new CountryCodesModelItem { "Bahamas", "qrc:///RegionFlags/png/BS.png", "1242" },
                        new CountryCodesModelItem { "Bahrain", "qrc:///RegionFlags/png/BH.png", "973" },
                        new CountryCodesModelItem { "Bangladesh", "qrc:///RegionFlags/png/BD.png", "880" },
                        new CountryCodesModelItem { "Barbados", "qrc:///RegionFlags/png/BB.png", "1246" },
                        new CountryCodesModelItem { "Belarus", "qrc:///RegionFlags/png/BY.png", "375" },
                        new CountryCodesModelItem { "Belgium", "qrc:///RegionFlags/png/BE.png", "32" },
                        new CountryCodesModelItem { "Belize", "qrc:///RegionFlags/png/BZ.png", "501" },
                        new CountryCodesModelItem { "Benin", "qrc:///RegionFlags/png/BJ.png", "229" },
                        new CountryCodesModelItem { "Bermuda", "qrc:///RegionFlags/png/BM.png", "1441" },
                        new CountryCodesModelItem { "Bhutan", "qrc:///RegionFlags/png/BT.png", "975" },
                        new CountryCodesModelItem { "Bolivia", "qrc:///RegionFlags/png/BO.png", "591" },
                        new CountryCodesModelItem { "Bosnia and Herzegovina", "qrc:///RegionFlags/png/BA.png", "387" },
                        new CountryCodesModelItem { "Botswana", "qrc:///RegionFlags/png/BW.png", "267" },
                        new CountryCodesModelItem { "Brazil", "qrc:///RegionFlags/png/BR.png", "55" },
                        new CountryCodesModelItem { "British Indian Ocean Territory", "qrc:///RegionFlags/png/IO.png", "246" },
                        new CountryCodesModelItem { "British Virgin Islands", "qrc:///RegionFlags/png/VG.png", "1284" },
                        new CountryCodesModelItem { "Brunei", "qrc:///RegionFlags/png/BN.png", "673" },
                        new CountryCodesModelItem { "Bulgaria", "qrc:///RegionFlags/png/BG.png", "359" },
                        new CountryCodesModelItem { "Burkina Faso", "qrc:///RegionFlags/png/BF.png", "226" },
                        new CountryCodesModelItem { "Burundi", "qrc:///RegionFlags/png/BI.png", "257" },
                        new CountryCodesModelItem { "Cambodia", "qrc:///RegionFlags/png/KH.png", "855" },
                        new CountryCodesModelItem { "Cameroon", "qrc:///RegionFlags/png/CM.png", "237" },
                        new CountryCodesModelItem { "Canada", "qrc:///RegionFlags/png/CA.png", "1" },
                        new CountryCodesModelItem { "Cape Verde", "qrc:///RegionFlags/png/CV.png", "238" },
                        new CountryCodesModelItem { "Caribbean Netherlands", "qrc:///RegionFlags/png/BQ.png", "599" },
                        new CountryCodesModelItem { "Cayman Islands", "qrc:///RegionFlags/png/KY.png", "1345" },
                        new CountryCodesModelItem { "Central African Republic", "qrc:///RegionFlags/png/CF.png", "236" },
                        new CountryCodesModelItem { "Chad", "qrc:///RegionFlags/png/TD.png", "235" },
                        new CountryCodesModelItem { "Chile", "qrc:///RegionFlags/png/CL.png", "56" },
                        new CountryCodesModelItem { "China", "qrc:///RegionFlags/png/CN.png", "86" },
                        new CountryCodesModelItem { "Christmas Island", "qrc:///RegionFlags/png/CX.png", "61" },
                        new CountryCodesModelItem { "Cocos Islands", "qrc:///RegionFlags/png/CC.png", "61" },
                        new CountryCodesModelItem { "Colombia", "qrc:///RegionFlags/png/CO.png", "57" },
                        new CountryCodesModelItem { "Comoros", "qrc:///RegionFlags/png/KM.png", "269" },
                        new CountryCodesModelItem { "Congo", "qrc:///RegionFlags/png/CD.png", "243" },
                        new CountryCodesModelItem { "Congo", "qrc:///RegionFlags/png/CG.png", "242" },
                        new CountryCodesModelItem { "Cook Islands", "qrc:///RegionFlags/png/CK.png", "682" },
                        new CountryCodesModelItem { "Costa Rica", "qrc:///RegionFlags/png/CR.png", "506" },
                        new CountryCodesModelItem { "Côte d’Ivoire", "qrc:///RegionFlags/png/CI.png", "225" },
                        new CountryCodesModelItem { "Croatia", "qrc:///RegionFlags/png/HR.png", "385" },
                        new CountryCodesModelItem { "Cuba", "qrc:///RegionFlags/png/CU.png", "53" },
                        new CountryCodesModelItem { "Curaçao", "qrc:///RegionFlags/png/CW.png", "599" },
                        new CountryCodesModelItem { "Cyprus", "qrc:///RegionFlags/png/CY.png", "357" },
                        new CountryCodesModelItem { "Czech Republic", "qrc:///RegionFlags/png/CZ.png", "420" },
                        new CountryCodesModelItem { "Denmark", "qrc:///RegionFlags/png/DK.png", "45" },
                        new CountryCodesModelItem { "Djibouti", "qrc:///RegionFlags/png/DJ.png", "253" },
                        new CountryCodesModelItem { "Dominica", "qrc:///RegionFlags/png/DM.png", "1767" },
                        new CountryCodesModelItem { "Dominican Republic", "qrc:///RegionFlags/png/DO.png", "1" },
                        new CountryCodesModelItem { "Ecuador", "qrc:///RegionFlags/png/EC.png", "593" },
                        new CountryCodesModelItem { "Egypt", "qrc:///RegionFlags/png/EG.png", "20" },
                        new CountryCodesModelItem { "El Salvador", "qrc:///RegionFlags/png/SV.png", "503" },
                        new CountryCodesModelItem { "Equatorial Guinea", "qrc:///RegionFlags/png/GQ.png", "240" },
                        new CountryCodesModelItem { "Eritrea", "qrc:///RegionFlags/png/ER.png", "291" },
                        new CountryCodesModelItem { "Estonia", "qrc:///RegionFlags/png/EE.png", "372" },
                        new CountryCodesModelItem { "Ethiopia", "qrc:///RegionFlags/png/ET.png", "251" },
                        new CountryCodesModelItem { "Falkland Islands", "qrc:///RegionFlags/png/FK.png", "500" },
                        new CountryCodesModelItem { "Faroe Islands", "qrc:///RegionFlags/png/FO.png", "298" },
                        new CountryCodesModelItem { "Fiji", "qrc:///RegionFlags/png/FJ.png", "679" },
                        new CountryCodesModelItem { "Finland", "qrc:///RegionFlags/png/FI.png", "358" },
                        new CountryCodesModelItem { "France", "qrc:///RegionFlags/png/FR.png", "33" },
                        new CountryCodesModelItem { "French Guiana", "qrc:///RegionFlags/png/GF.png", "594" },
                        new CountryCodesModelItem { "French Polynesia", "qrc:///RegionFlags/png/PF.png", "689" },
                        new CountryCodesModelItem { "Gabon", "qrc:///RegionFlags/png/GA.png", "241" },
                        new CountryCodesModelItem { "Gambia", "qrc:///RegionFlags/png/GM.png", "220" },
                        new CountryCodesModelItem { "Georgia", "qrc:///RegionFlags/png/GE.png", "995" },
                        new CountryCodesModelItem { "Germany", "qrc:///RegionFlags/png/DE.png", "49" },
                        new CountryCodesModelItem { "Ghana", "qrc:///RegionFlags/png/GH.png", "233" },
                        new CountryCodesModelItem { "Gibraltar", "qrc:///RegionFlags/png/GI.png", "350" },
                        new CountryCodesModelItem { "Greece", "qrc:///RegionFlags/png/GR.png", "30" },
                        new CountryCodesModelItem { "Greenland", "qrc:///RegionFlags/png/GL.png", "299" },
                        new CountryCodesModelItem { "Grenada", "qrc:///RegionFlags/png/GD.png", "1473" },
                        new CountryCodesModelItem { "Guadeloupe", "qrc:///RegionFlags/png/GP.png", "590" },
                        new CountryCodesModelItem { "Guam", "qrc:///RegionFlags/png/GU.png", "1671" },
                        new CountryCodesModelItem { "Guatemala", "qrc:///RegionFlags/png/GT.png", "502" },
                        new CountryCodesModelItem { "Guernsey", "qrc:///RegionFlags/png/GG.png", "44" },
                        new CountryCodesModelItem { "Guinea", "qrc:///RegionFlags/png/GN.png", "224" },
                        new CountryCodesModelItem { "Guinea-Bissau", "qrc:///RegionFlags/png/GW.png", "245" },
                        new CountryCodesModelItem { "Guyana", "qrc:///RegionFlags/png/GY.png", "592" },
                        new CountryCodesModelItem { "Haiti", "qrc:///RegionFlags/png/HT.png", "509" },
                        new CountryCodesModelItem { "Honduras", "qrc:///RegionFlags/png/HN.png", "504" },
                        new CountryCodesModelItem { "Hong Kong", "qrc:///RegionFlags/png/HK.png", "852" },
                        new CountryCodesModelItem { "Hungary", "qrc:///RegionFlags/png/HU.png", "36" },
                        new CountryCodesModelItem { "Iceland", "qrc:///RegionFlags/png/IS.png", "354" },
                        new CountryCodesModelItem { "India", "qrc:///RegionFlags/png/IN.png", "91" },
                        new CountryCodesModelItem { "Indonesia", "qrc:///RegionFlags/png/ID.png", "62" },
                        new CountryCodesModelItem { "Iran", "qrc:///RegionFlags/png/IR.png", "98" },
                        new CountryCodesModelItem { "Iraq", "qrc:///RegionFlags/png/IQ.png", "964" },
                        new CountryCodesModelItem { "Ireland", "qrc:///RegionFlags/png/IE.png", "353" },
                        new CountryCodesModelItem { "Isle of Man", "qrc:///RegionFlags/png/IM.png", "44" },
                        new CountryCodesModelItem { "Israel", "qrc:///RegionFlags/png/IL.png", "972" },
                        new CountryCodesModelItem { "Italy", "qrc:///RegionFlags/png/IT.png", "39" },
                        new CountryCodesModelItem { "Jamaica", "qrc:///RegionFlags/png/JM.png", "1876" },
                        new CountryCodesModelItem { "Japan", "qrc:///RegionFlags/png/JP.png", "81" },
                        new CountryCodesModelItem { "Jersey", "qrc:///RegionFlags/png/JE.png", "44" },
                        new CountryCodesModelItem { "Jordan", "qrc:///RegionFlags/png/JO.png", "962" },
                        new CountryCodesModelItem { "Kazakhstan", "qrc:///RegionFlags/png/KZ.png", "7" },
                        new CountryCodesModelItem { "Kenya", "qrc:///RegionFlags/png/KE.png", "254" },
                        new CountryCodesModelItem { "Kiribati", "qrc:///RegionFlags/png/KI.png", "686" },
                        new CountryCodesModelItem { "Kosovo", "qrc:///RegionFlags/png/XK.png", "383" },
                        new CountryCodesModelItem { "Kuwait", "qrc:///RegionFlags/png/KW.png", "965" },
                        new CountryCodesModelItem { "Kyrgyzstan", "qrc:///RegionFlags/png/KG.png", "996" },
                        new CountryCodesModelItem { "Laos", "qrc:///RegionFlags/png/LA.png", "856" },
                        new CountryCodesModelItem { "Latvia", "qrc:///RegionFlags/png/LV.png", "371" },
                        new CountryCodesModelItem { "Lebanon", "qrc:///RegionFlags/png/LB.png", "961" },
                        new CountryCodesModelItem { "Lesotho", "qrc:///RegionFlags/png/LS.png", "266" },
                        new CountryCodesModelItem { "Liberia", "qrc:///RegionFlags/png/LR.png", "231" },
                        new CountryCodesModelItem { "Libya", "qrc:///RegionFlags/png/LY.png", "218" },
                        new CountryCodesModelItem { "Liechtenstein", "qrc:///RegionFlags/png/LI.png", "423" },
                        new CountryCodesModelItem { "Lithuania", "qrc:///RegionFlags/png/LT.png", "370" },
                        new CountryCodesModelItem { "Luxembourg", "qrc:///RegionFlags/png/LU.png", "352" },
                        new CountryCodesModelItem { "Macau", "qrc:///RegionFlags/png/MO.png", "853" },
                        new CountryCodesModelItem { "Macedonia", "qrc:///RegionFlags/png/MK.png", "389" },
                        new CountryCodesModelItem { "Madagascar", "qrc:///RegionFlags/png/MG.png", "261" },
                        new CountryCodesModelItem { "Malawi", "qrc:///RegionFlags/png/MW.png", "265" },
                        new CountryCodesModelItem { "Malaysia", "qrc:///RegionFlags/png/MY.png", "60" },
                        new CountryCodesModelItem { "Maldives", "qrc:///RegionFlags/png/MV.png", "960" },
                        new CountryCodesModelItem { "Mali", "qrc:///RegionFlags/png/ML.png", "223" },
                        new CountryCodesModelItem { "Malta", "qrc:///RegionFlags/png/MT.png", "356" },
                        new CountryCodesModelItem { "Marshall Islands", "qrc:///RegionFlags/png/MH.png", "692" },
                        new CountryCodesModelItem { "Martinique", "qrc:///RegionFlags/png/MQ.png", "596" },
                        new CountryCodesModelItem { "Mauritania", "qrc:///RegionFlags/png/MR.png", "222" },
                        new CountryCodesModelItem { "Mauritius", "qrc:///RegionFlags/png/MU.png", "230" },
                        new CountryCodesModelItem { "Mayotte", "qrc:///RegionFlags/png/YT.png", "262" },
                        new CountryCodesModelItem { "Mexico", "qrc:///RegionFlags/png/MX.png", "52" },
                        new CountryCodesModelItem { "Micronesia", "qrc:///RegionFlags/png/FM.png", "691" },
                        new CountryCodesModelItem { "Moldova", "qrc:///RegionFlags/png/MD.png", "373" },
                        new CountryCodesModelItem { "Monaco", "qrc:///RegionFlags/png/MC.png", "377" },
                        new CountryCodesModelItem { "Mongolia", "qrc:///RegionFlags/png/MN.png", "976" },
                        new CountryCodesModelItem { "Montenegro", "qrc:///RegionFlags/png/ME.png", "382" },
                        new CountryCodesModelItem { "Montserrat", "qrc:///RegionFlags/png/MS.png", "1664" },
                        new CountryCodesModelItem { "Morocco", "qrc:///RegionFlags/png/MA.png", "212" },
                        new CountryCodesModelItem { "Mozambique", "qrc:///RegionFlags/png/MZ.png", "258" },
                        new CountryCodesModelItem { "Myanmar", "qrc:///RegionFlags/png/MM.png", "95" },
                        new CountryCodesModelItem { "Namibia", "qrc:///RegionFlags/png/NA.png", "264" },
                        new CountryCodesModelItem { "Nauru", "qrc:///RegionFlags/png/NR.png", "674" },
                        new CountryCodesModelItem { "Nepal", "qrc:///RegionFlags/png/NP.png", "977" },
                        new CountryCodesModelItem { "Netherlands", "qrc:///RegionFlags/png/NL.png", "31" },
                        new CountryCodesModelItem { "New Caledonia", "qrc:///RegionFlags/png/NC.png", "687" },
                        new CountryCodesModelItem { "New Zealand", "qrc:///RegionFlags/png/NZ.png", "64" },
                        new CountryCodesModelItem { "Nicaragua", "qrc:///RegionFlags/png/NI.png", "505" },
                        new CountryCodesModelItem { "Niger", "qrc:///RegionFlags/png/NE.png", "227" },
                        new CountryCodesModelItem { "Nigeria", "qrc:///RegionFlags/png/NG.png", "234" },
                        new CountryCodesModelItem { "Niue", "qrc:///RegionFlags/png/NU.png", "683" },
                        new CountryCodesModelItem { "Norfolk Island", "qrc:///RegionFlags/png/NF.png", "672" },
                        new CountryCodesModelItem { "North Korea", "qrc:///RegionFlags/png/KP.png", "850" },
                        new CountryCodesModelItem { "Northern Mariana Islands", "qrc:///RegionFlags/png/MP.png", "1670" },
                        new CountryCodesModelItem { "Norway", "qrc:///RegionFlags/png/NO.png", "47" },
                        new CountryCodesModelItem { "Oman", "qrc:///RegionFlags/png/OM.png", "968" },
                        new CountryCodesModelItem { "Pakistan", "qrc:///RegionFlags/png/PK.png", "92" },
                        new CountryCodesModelItem { "Palau", "qrc:///RegionFlags/png/PW.png", "680" },
                        new CountryCodesModelItem { "Palestine", "qrc:///RegionFlags/png/PS.png", "970" },
                        new CountryCodesModelItem { "Panama", "qrc:///RegionFlags/png/PA.png", "507" },
                        new CountryCodesModelItem { "Papua New Guinea", "qrc:///RegionFlags/png/PG.png", "675" },
                        new CountryCodesModelItem { "Paraguay", "qrc:///RegionFlags/png/PY.png", "595" },
                        new CountryCodesModelItem { "Peru", "qrc:///RegionFlags/png/PE.png", "51" },
                        new CountryCodesModelItem { "Philippines", "qrc:///RegionFlags/png/PH.png", "63" },
                        new CountryCodesModelItem { "Poland", "qrc:///RegionFlags/png/PL.png", "48" },
                        new CountryCodesModelItem { "Portugal", "qrc:///RegionFlags/png/PT.png", "351" },
                        new CountryCodesModelItem { "Puerto Rico", "qrc:///RegionFlags/png/PR.png", "1" },
                        new CountryCodesModelItem { "Qatar", "qrc:///RegionFlags/png/QA.png", "974" },
                        new CountryCodesModelItem { "Réunion", "qrc:///RegionFlags/png/RE.png", "262" },
                        new CountryCodesModelItem { "Romania", "qrc:///RegionFlags/png/RO.png", "40" },
                        new CountryCodesModelItem { "Russia", "qrc:///RegionFlags/png/RU.png", "7" },
                        new CountryCodesModelItem { "Rwanda", "qrc:///RegionFlags/png/RW.png", "250" },
                        new CountryCodesModelItem { "Saint Barthélemy", "qrc:///RegionFlags/png/BL.png", "590" },
                        new CountryCodesModelItem { "Saint Helena", "qrc:///RegionFlags/png/SH.png", "290" },
                        new CountryCodesModelItem { "Saint Kitts and Nevis", "qrc:///RegionFlags/png/KN.png", "1869" },
                        new CountryCodesModelItem { "Saint Lucia", "qrc:///RegionFlags/png/LC.png", "1758" },
                        new CountryCodesModelItem { "Saint Martin", "qrc:///RegionFlags/png/MF.png", "590" },
                        new CountryCodesModelItem { "Saint Pierre and Miquelon", "qrc:///RegionFlags/png/PM.png", "508" },
                        new CountryCodesModelItem { "Saint Vincent and the Grenadines", "qrc:///RegionFlags/png/VC.png", "1784" },
                        new CountryCodesModelItem { "Samoa", "qrc:///RegionFlags/png/WS.png", "685" },
                        new CountryCodesModelItem { "San Marino", "qrc:///RegionFlags/png/SM.png", "378" },
                        new CountryCodesModelItem { "São Tomé and Príncipe", "qrc:///RegionFlags/png/ST.png", "239" },
                        new CountryCodesModelItem { "Saudi Arabia", "qrc:///RegionFlags/png/SA.png", "966" },
                        new CountryCodesModelItem { "Senegal", "qrc:///RegionFlags/png/SN.png", "221" },
                        new CountryCodesModelItem { "Serbia", "qrc:///RegionFlags/png/RS.png", "381" },
                        new CountryCodesModelItem { "Seychelles", "qrc:///RegionFlags/png/SC.png", "248" },
                        new CountryCodesModelItem { "Sierra Leone", "qrc:///RegionFlags/png/SL.png", "232" },
                        new CountryCodesModelItem { "Singapore", "qrc:///RegionFlags/png/SG.png", "65" },
                        new CountryCodesModelItem { "Sint Maarten", "qrc:///RegionFlags/png/SX.png", "1721" },
                        new CountryCodesModelItem { "Slovakia", "qrc:///RegionFlags/png/SK.png", "421" },
                        new CountryCodesModelItem { "Slovenia", "qrc:///RegionFlags/png/SI.png", "386" },
                        new CountryCodesModelItem { "Solomon Islands", "qrc:///RegionFlags/png/SB.png", "677" },
                        new CountryCodesModelItem { "Somalia", "qrc:///RegionFlags/png/SO.png", "252" },
                        new CountryCodesModelItem { "South Africa", "qrc:///RegionFlags/png/ZA.png", "27" },
                        new CountryCodesModelItem { "South Korea", "qrc:///RegionFlags/png/KR.png", "82" },
                        new CountryCodesModelItem { "South Sudan", "qrc:///RegionFlags/png/SS.png", "211" },
                        new CountryCodesModelItem { "Spain", "qrc:///RegionFlags/png/ES.png", "34" },
                        new CountryCodesModelItem { "Sri Lanka", "qrc:///RegionFlags/png/LK.png", "94" },
                        new CountryCodesModelItem { "Sudan", "qrc:///RegionFlags/png/SD.png", "249" },
                        new CountryCodesModelItem { "Suriname", "qrc:///RegionFlags/png/SR.png", "597" },
                        new CountryCodesModelItem { "Svalbard and Jan Mayen", "qrc:///RegionFlags/png/SJ.png", "47" },
                        new CountryCodesModelItem { "Swaziland", "qrc:///RegionFlags/png/SZ.png", "268" },
                        new CountryCodesModelItem { "Sweden", "qrc:///RegionFlags/png/SE.png", "46" },
                        new CountryCodesModelItem { "Switzerland", "qrc:///RegionFlags/png/CH.png", "41" },
                        new CountryCodesModelItem { "Syria", "qrc:///RegionFlags/png/SY.png", "963" },
                        new CountryCodesModelItem { "Taiwan", "qrc:///RegionFlags/png/TW.png", "886" },
                        new CountryCodesModelItem { "Tajikistan", "qrc:///RegionFlags/png/TJ.png", "992" },
                        new CountryCodesModelItem { "Tanzania", "qrc:///RegionFlags/png/TZ.png", "255" },
                        new CountryCodesModelItem { "Thailand", "qrc:///RegionFlags/png/TH.png", "66" },
                        new CountryCodesModelItem { "Timor-Leste", "qrc:///RegionFlags/png/TL.png", "670" },
                        new CountryCodesModelItem { "Togo", "qrc:///RegionFlags/png/TG.png", "228" },
                        new CountryCodesModelItem { "Tokelau", "qrc:///RegionFlags/png/TK.png", "690" },
                        new CountryCodesModelItem { "Tonga", "qrc:///RegionFlags/png/TO.png", "676" },
                        new CountryCodesModelItem { "Trinidad and Tobago", "qrc:///RegionFlags/png/TT.png", "1868" },
                        new CountryCodesModelItem { "Tunisia", "qrc:///RegionFlags/png/TN.png", "216" },
                        new CountryCodesModelItem { "Turkey", "qrc:///RegionFlags/png/TR.png", "90" },
                        new CountryCodesModelItem { "Turkmenistan", "qrc:///RegionFlags/png/TM.png", "993" },
                        new CountryCodesModelItem { "Turks and Caicos Islands", "qrc:///RegionFlags/png/TC.png", "1649" },
                        new CountryCodesModelItem { "Tuvalu", "qrc:///RegionFlags/png/TV.png", "688" },
                        new CountryCodesModelItem { "U.S. Virgin Islands", "qrc:///RegionFlags/png/VI.png", "1340" },
                        new CountryCodesModelItem { "Uganda", "qrc:///RegionFlags/png/UG.png", "256" },
                        new CountryCodesModelItem { "Ukraine", "qrc:///RegionFlags/png/UA.png", "380" },
                        new CountryCodesModelItem { "United Arab Emirates", "qrc:///RegionFlags/png/AE.png", "971" },
                        new CountryCodesModelItem { "United Kingdom", "qrc:///RegionFlags/png/GB.png", "44" },
                        new CountryCodesModelItem { "United States", "qrc:///RegionFlags/png/US.png", "1" },
                        new CountryCodesModelItem { "Uruguay", "qrc:///RegionFlags/png/UY.png", "598" },
                        new CountryCodesModelItem { "Uzbekistan", "qrc:///RegionFlags/png/UZ.png", "998" },
                        new CountryCodesModelItem { "Vanuatu", "qrc:///RegionFlags/png/VU.png", "678" },
                        new CountryCodesModelItem { "Vatican City", "qrc:///RegionFlags/png/VA.png", "39" },
                        new CountryCodesModelItem { "Venezuela", "qrc:///RegionFlags/png/VE.png", "58" },
                        new CountryCodesModelItem { "Vietnam", "qrc:///RegionFlags/png/VN.png", "84" },
                        new CountryCodesModelItem { "Wallis and Futuna", "qrc:///RegionFlags/png/WF.png", "681" },
                        new CountryCodesModelItem { "Western Sahara", "qrc:///RegionFlags/png/EH.png", "212" },
                        new CountryCodesModelItem { "Yemen", "qrc:///RegionFlags/png/YE.png", "967" },
                        new CountryCodesModelItem { "Zambia", "qrc:///RegionFlags/png/ZM.png", "260" },
                        new CountryCodesModelItem { "Zimbabwe", "qrc:///RegionFlags/png/ZW.png", "263" },
                        new CountryCodesModelItem { "Åland Islands", "qrc:///RegionFlags/png/AX.png", "358" },
                    });
}
